[boris]
  version = 1

[build.dist-7-10]

[build.branches-7-10]

[build.validate]
  command = [["validate-respect"]]

[build.submodules]
  command = [["dangling-refs"]]

[build.submodules-branches]
  command = [["dangling-refs"]]

[build.rebased]
  command = [["rebased"]]
